language: node_js
node_js:
  - "10" 
  - "8"
  - "6"

cache:
  directories:
    - "node_modules"

if: tag IS blank

jobs:
  include:
    - stage: npm release

      if: branch = master

      script: echo publishing...

      before_deploy: 
        - export VERSION_TAG=$(git ls-remote origin | grep "$TRAVIS_COMMIT\s\+refs/tags/v[0-9]\+\.[0-9]\+\.[0-9]\+\^{}$")
        - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
        - npm i --global otp-cli
        - export NPM_OTP=$(otp-cli totp generate -k "$NPM_OTP_SECRET")
      deploy:
        provider: script
        script: if [ -n "$VERSION_TAG" ]; then npm publish --access public --otp "$NPM_OTP"; else echo commit not tagged; fi
        skip_cleanup: true
      after_deploy: rm ~/.npmrc
